---
# "gemma", "llama3.2", "llama3.2", "qwen3", "qwen25", "mistral"
model: "gemma"

# ru/eng-zero/one/few-shot
prompt: "prompts/ru-few-shot"

seed: 42

# max length for input text (words) / default 512
input_text_max_len: 512

labels_path: "sem_types.csv"
labels_column: "label"

dataset:
  path: "sti-team/rwt-rutabert"
  data_column: "column_data"
  label_column: "label"
  split: "test"

# Deterministic output
sampling:
  max_tokens: 20
  temperature: 0.0
  top_p: 1.0
  top_k: 0

optim:
  max_num_seqs: 256 # process at most 256 sequences per forward pass.
  cpu_offload_gb: 0 # if gpu memory not enough.
  gpu_memory_utilization: 0.9 # from 0.0 to 1.0 / default 0.9.

inference_score:
  n_tests: 100
  average: ["micro", "macro", "weighted"]
